### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by waternight1029** [mluogh/grontown#43]
I met an error, but cannot tell whether it is related to my environment
ERROR
Internal Server Error
ApiError: Internal Server Error
    at catchErrorCodes (http://localhost:3001/static/js/bundle.js:4133:11)
    at http://localhost:3001/static/js/bundle.js:4176:9

**Comment by mluogh** [comment]
Not sure where the :3001 is coming from.

Are you running the eastworld backend? Is there an error there? Maybe you didn't copy an API key?
